CREATE SCHEMA IF NOT EXISTS lab2;
ALTER DATABASE lab2db SET search_path = 'lab2, public';

CREATE ROLE migrate NOINHERIT LOGIN PASSWORD 'migrate' NOCREATEDB;
GRANT USAGE ON SCHEMA lab2 TO migrate;
GRANT CREATE ON SCHEMA lab2 TO migrate;

CREATE ROLE app NOINHERIT LOGIN PASSWORD 'app' NOCREATEDB;
GRANT USAGE ON SCHEMA lab2 TO app;
ALTER DEFAULT PRIVILEGES FOR ROLE migrate IN SCHEMA lab2 GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
